# Frontend Netlify configuration

# Functions configuration
[functions]
  directory = "../backend/functions"
  node_bundler = "esbuild"
  external_node_modules = ["express", "serverless-http", "dotenv", "auth0", "express-jwt", "rate-limiter-flexible", "express-jwt-authz", "jwks-rsa", "mongodb", "mongoose", "stripe", "winston", "faunadb"]

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Cache control for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://*.auth0.com https://*.netlify.app;"