# Netlify Environment Variables Configuration
# This file is used to configure environment variables for different deployment contexts
# Do not commit sensitive values to version control
# Use this file as a template and create a netlify.env.production.toml file for production values

# Production environment variables
[context.production.environment]
  NODE_ENV = "production"
  API_URL = "https://your-production-domain.netlify.app/.netlify/functions/api"
  FRONTEND_URL = "https://your-production-domain.netlify.app"
  # The following variables should be set in the Netlify UI
  # AUTH0_DOMAIN = ""
  # AUTH0_CLIENT_ID = ""
  # AUTH0_CLIENT_SECRET = ""
  # AUTH0_CALLBACK_URL = ""
  # AUTH0_AUDIENCE = ""
  # FAUNADB_SECRET = ""
  # STRIPE_SECRET_KEY = ""
  # STRIPE_WEBHOOK_SECRET = ""

# Branch deploy environment variables
[context.branch-deploy.environment]
  NODE_ENV = "staging"
  API_URL = "https://branch-name--your-site-name.netlify.app/.netlify/functions/api"
  FRONTEND_URL = "https://branch-name--your-site-name.netlify.app"

# Deploy preview environment variables
[context.deploy-preview.environment]
  NODE_ENV = "staging"
  API_URL = "https://deploy-preview-pr-number--your-site-name.netlify.app/.netlify/functions/api"
  FRONTEND_URL = "https://deploy-preview-pr-number--your-site-name.netlify.app"

# Development environment variables
[context.dev.environment]
  NODE_ENV = "development"
  API_URL = "http://localhost:8888/.netlify/functions/api"
  FRONTEND_URL = "http://localhost:3000"