name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
      - development
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Install dependencies
        working-directory: frontend
        run: npm ci
      - name: Build
        working-directory: frontend
        run: npm run build
      - name: Setup CNAME
        run: echo "${{ github.ref == 'refs/heads/main' && 'threefold.store' || 'dev.threefold.store' }}" > frontend/dist/CNAME
      - name: Configure Pages
        uses: actions/configure-pages@v4
        with:
          token: ${{ secrets.PAGES_PAT }}
          enablement: workflow
          custom-domain: ${{ github.ref == 'refs/heads/main' && 'threefold.store' || 'dev.threefold.store' }}
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: frontend/dist
          artifact_name: github-pages
      - name: Deploy Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.PAGES_PAT }}
          artifact_name: github-pages
