name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
      - development
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        working-directory: frontend
        run: npm ci
      - name: Build
        working-directory: frontend
        run: npm run build
      - name: Setup CNAME
        run: echo "${{ github.ref == 'refs/heads/main' && 'threefold.store' || 'dev.threefold.store' }}" > frontend/dist/CNAME
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: frontend/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: frontend/dist
      - name: Configure Pages
        uses: actions/configure-pages@v3
        with:
          token: ${{ secrets.PAGES_PAT }}
          enablement: workflow
          custom-domain: ${{ github.ref == 'refs/heads/main' && 'threefold.store' || 'dev.threefold.store' }}
      - name: Deploy Pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.PAGES_PAT }}
          artifact_name: dist
